language: c++

services:
  - docker

before_install:
  - docker build -t icluesu2020/nl-positivity:latest .
  - docker run --name nl_positivity_bash --rm -it -d icluesu2020/nl-positivity:latest bash
  - docker ps

script:
  - ls
  - pwd
  - docker exec -t -d nlnum_bash cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release --build cmake-build-release --target test-nl-positivity -- -j 2 .
  - docker exec -t -d nlnum_bash time OMP_CANCELLATION=true ./cmake-build-release/tests/cmake-build-debug/test-nl-positivity
